#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartUserControl, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,    ,               sensorAnalog)
#pragma config(Sensor, dgtl12, ,               sensorDigitalHighImpedance)
#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port4,            ,             tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,            ,             tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port6,            ,             tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)

#include "Vex_Competition_Includes.c"

//FL = 2 FR = 3
//BL = 4 BR = 5

int deWine(int inp){
	if((inp < 15) && (inp > -15)){
		return 0;
	}
	return inp;
}

void pre_auton(){
	bStopTasksBetweenModes = true;
}

task autonomous(){

}

task usercontrol()
{
	while(true){
		//Wheels
		motor[port2] = deWine(vexRT[Ch3] * 0.9 + vexRT[Ch1]);
		motor[port3] = deWine(vexRT[Ch3] * 0.9 - vexRT[Ch1]);
		motor[port4] = deWine(vexRT[Ch3] * 0.9 + vexRT[Ch1]);
		motor[port5] = deWine(vexRT[Ch3] * 0.9 - vexRT[Ch1]);

		motor[portn] = deWine(vexRT[Ch4]);

		//Belt
		if(vexRT[Btn5U]){
			motor[port6] = 127;
		}else if(vexRT[Btn5D]){
			motor[port6] = -127;
		}else{
			motor[port6] = 0;
		}

		//Shooter
		if(vexRT[Btn6U]){
			motor[port8] = -127;
			motor[port9] = -127;
		}else if(vexRT[Btn6D]){
			motor[port8] = 127;
			motor[port9] = 127;
		}else{
			motor[port8] = 0;
			motor[port9] = 0;
		}
	}
}
