#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartUserControl, baudRate4800, IOPins, None, None)
#pragma config(Sensor, dgtl1,  ,               sensorSONAR_cm)
#pragma config(Sensor, dgtl12, ,               sensorDigitalHighImpedance)
#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,            ,             tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port4,            ,             tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,            ,             tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port6,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(125)

#include "Vex_Competition_Includes.c"

//FL = 2 FR = 3
//BL = 4 BR = 5

int menuCurr = 0;
int menuMax = 1;
bool backlightEnabled = true;
bool backlightFlashing = false;
int backlightFlashCount = 0;
int backlightMaxCount = 1000;

void go(int v0, int v1, int v2, int v3){
	motor[port2] = v0;
	motor[port3] = v1;
	motor[port4] = v2;
	motor[port5] = v3;
}

int deWine(int inp){
	if((inp < 15) && (inp > -15)){
		return 0;
	}
	return inp;
}

void updateLCD(){
	clearLCDLine(0);
	clearLCDLine(1);

	if(backlightFlashing){
		backlightFlashCount++;
		if(backlightFlashCount > backlightMaxCount) backlightFlashCount = 0;
		if(backlightFlashCount < (backlightFlashCount / 2)) bLCDBacklight = true;
		else bLCDBacklight = false;
	}else{
		bLCDBacklight = backlightEnabled;
	}

	if(SensorValue[dgtl1] == 0) menuCurr++;
	else if(SensorValue[dgtl1] == 2) menuCurr--;

	if(menuCurr > menuMax) menuCurr = 0;
	else if(menuCurr < 0) menuCurr = menuMax;

	if(menuCurr == 0){
		displayLCDString(0, 0, "Primary: ");
		displayNextLCDNumber((nImmediateBatteryLevel) / 1000.0);
		displayNextLCDString("V");
		displayLCDString(0, 0, "Backup: ");
		displayNextLCDNumber((BackupBatteryLevel) / 1000.0);
		displayNextLCDString("V");
	}else if(menuCurr == 1){

	}
}

void pre_auton(){
	bStopTasksBetweenModes = true;
}

task autonomous(){
	go(127, 127, 127, 127);
	wait1Msec(2000);
	go(0, 0, 0, 0);
}

task usercontrol()
{
	while(true){
		updateLCD();

		//Wheels
		motor[port2] = deWine(vexRT[Ch3]);
		motor[port3] = deWine(vexRT[Ch2]);
		motor[port4] = deWine(vexRT[Ch3]);
		motor[port5] = deWine(vexRT[Ch2]);

		//Arm
		if(vexRT[Btn6U]){
			motor[port6] = 127;
		}else if(vexRT[Btn6D]){
			motor[port6] = -127;
		}else{
			motor[port6] = 0;
		}
	}
}
